:slug: separate-out-test-suites
= Separate out test suites

If running different test suites against the same build, separating them out to different "test suites" would improve the quality of data analysis throughout our system.

== What is a test suite?

Teams regularly group their test cases into logical groups based on one or combination of:

. The _type_ of test (e.g., unit tests vs. UI tests.)
. The _tech stack_ used to run those tests (e.g., Maven for unit tests vs. Cypress for UI tests.)
. The _when_ and _where_ they run (e.g., nightly vs every change, in the CI system vs in the staging environment.)

If thinking about test suites this way, the definition will be more straightforward: for example, all the Maven unit tests become one test suite, and all the Cypress UI tests become another test suite.

== How do you benefit from test suites?

When you record test suites, you can focus on test sessions & issues from a particular test suite.

== How do you record test suite?

. Invoke the `smart-tests record tests` command, then specify the additional `--test-suite` option and give it a test suite name.
+
`$ smart-tests record tests --test-suite "ui tests" ...`

. If using the `smart-tests record session` command explicitly as per xref:send-data-to-smart-tests:record-test-results/manage-complex-test-session-layouts.adoc[Managing complex test session layout], then the `--test-suite` option should be used with that command instead of `record tests`.
