:slug: use-the-cli-with-a-public-repository
= Use the CLI with a public repository

Authentication between the {PRODUCT} CLI and {PRODUCT} API typically requires an API key. However, API keys cannot be used for open-source projects in public repositories since anyone can retrieve an API key by opening a pull request.

To solve this problem for open-source projects, {PRODUCT} offers another authentication mechanism called _tokenless authentication_. Instead of using a static token, tokenless authentication uses a CI/CD service provider's public API to verify if tests are actually running in CI. With this feature, OSS contributors can analyze and optimize test execution without a static {PRODUCT} API token.

[NOTE]
--
In November 2022 {PRODUCT} added support for OpenID Connect for authentication.

If tokenless authentication was implemented before November 2022, refer to xref:send-data-to-smart-tests:getting-started/migration-to-github-oidc-auth.adoc[Update tokenless authentication to use GitHub OIDC].
--
[#setup-tokenless-authentication]
== Set up tokenless authentication

=== Prerequisites

If your project is open source, and you want to use {PRODUCT};

* The open-source project needs to be hosted in a public GitHub repository.
* The open-source project needs to use GitHub Actions for {CI}.

=== Preparation

. http://app.launchableinc.com/signup[Sign up] and create your xref:concepts:organization.adoc[Organization] and xref:concepts:workspace.adoc[Workspace].
. https://www.launchableinc.com/support[Contact us] to enable tokenless authentication for your project. We need to know your {PRODUCT} organization, {PRODUCT} workspace, and GitHub repository URL.
. Update your GitHub Actions YAML.
. Start using {PRODUCT} in your open-source project.

==== GitHub Actions YAML configuration

Once tokenless authentication is enabled for your project, do the following:

. Configure environment variables in your CI pipeline:

.. `SMART_TESTS_ORGANIZATION`: {PRODUCT} organization name
.. `SMART_TESTS_WORKSPACE`: {PRODUCT} workspace name
.. `EXPERIMENTAL_GITHUB_OIDC_TOKEN_AUTH`: Set this to 1

. Add the `permissions` section of your GitHub Actions YAML file.

Tokenless authentication relies on OpenID Connect (OIDC) tokens. To use an OIDC token in GitHub Actions, you need to configure permissions to retrieve it. As described in the https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings[GitHub Help Article], `id-token: write` permission needs to be added.

This permission can be added for one job or to the entire workflow:

[source,role="default=expand"]
----
name: Verify Smart Tests tokenless authentication

on:
  pull_request:
    paths:
      - gradle/**

env:
  SMART_TESTS_ORGANIZATION: "examples"
  SMART_TESTS_WORKSPACE: "gradle"
  EXPERIMENTAL_GITHUB_OIDC_TOKEN_AUTH: 1

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: {PRODUCT}
        run: |
          pip3 install --user smart-tests~=1.0
          export PATH=~/.local/bin:$PATH
          smart-tests verify
        working-directory: ./gradle
----

== About OpenID Connect (OIDC)

[NOTE]
--
In November 2022 {PRODUCT} added support for OpenID Connect for authentication.

If tokenless authentication was implemented before November 2022, refer to xref:send-data-to-smart-tests:getting-started/migration-to-github-oidc-auth.adoc[Update tokenless authentication to use GitHub OIDC].
--
